#ifndef ERROR_CODES_ENUM_H
#define ERROR_CODES_ENUM_H

enum errors {
    NOT_ENOUGH_ARGUMENTS = 1,
    CANNOT_OPEN_PASSWD_FILE,
    USER_NOT_FOUND,
    MEMORY_ALLOCATION_ERROR,
    READING_ERROR,
    UNEXPECTED_EOF,
};

#endif
